### PR TITLE
chore(README): update `package.json` example with `module.json` subpath

### PR DESCRIPTION
**Pull request by cpreston321**
Updated README.md example package.json.

CC: @pi0

### CODE REVIEW

**Comment by pi0** [comment]
It isn't used for modules currently. FYI we generate `dist/module.json` that might be more useful to expose as subpath.

**Comment by cpreston321** [comment]
Got it! Thanks

**Comment by cpreston321** [comment]
@pi0 updated!

**Comment by pi0** [comment]
Thanks again for PR but i think we don't need to expose it at this point and increase complexity of starter package.json. There are programmatic ways to access module meta from wrapper.

**Pull request closed without merging**
